services:
  - type: web
    name: paygate-api
    runtime: docker
    plan: free

  - type: worker
    name: paygate-worker
    runtime: php
    plan: docker
    startCommand: php artisan queue:work --tries=3